In [1]:
import numpy as np

## Starting point

In [2]:
x0 = np.array([-2,-2])

## System

In [3]:
b = np.array([2,-8])

In [4]:
A = np.array([[3,2],[2,6]])

In [5]:
A

array([[3, 2],
       [2, 6]])

In [6]:
b

array([ 2, -8])

## Residual

In [7]:
def r(x):
    return  b- A.dot(x)

## Line search

In [8]:
def alpha(x):
    return (r(x).dot(r(x)))/(r(x).dot(A.dot(r(x))))

In [9]:
x1 = x0 + alpha(x0) * r(x0)

In [10]:
x1

array([ 0.08      , -0.61333333])

In [11]:
x2 = x1 + alpha(x1) * r(x1)

In [12]:
x2

array([ 1.00444444, -2.        ])

In [13]:
x3 = x2 + alpha(x2) * r(x2)

In [17]:
x3

array([ 1.52213333, -1.65487407])

In [20]:
x4 = x3 + alpha(x3) * r(x3)

In [21]:
x4

array([ 1.75221728, -2.        ])

In [22]:
x5 = x4 + alpha(x4) * r(x4)

In [23]:
x5

array([ 1.8810643 , -1.91410199])

In [24]:
x6 = x5 + alpha(x5) * r(x5)

In [25]:
x6

array([ 1.93832964, -2.        ])